In [2]:
import pandas as pd
import numpy as np
import datetime
import investpy

In [ ]:
start_date =

In [19]:
symbol = 'PLC'
country = 'VietNam'
investpy.stocks.get_stock_dividends(symbol,country)

         Date  Dividend    Type Payment Date   Yield
0  2021-06-01     500.0    None          NaT    None
1  2020-12-16    1000.0    None          NaT    None
2  2020-07-15    1500.0  annual   2020-07-24   8.88%
3  2019-06-13    1600.0  annual   2019-06-28   9.94%
4  2018-06-14    2000.0  annual   2018-06-29  10.31%
5  2017-06-15    2000.0  annual   2017-06-30   6.78%
6  2015-12-11    3000.0  annual   2015-12-31   7.79%
7  2015-07-06     300.0    None          NaT    None
8  2014-12-26    2700.0    None          NaT    None
9  2014-06-11    1500.0  annual   2014-06-30   6.98%
10 2013-06-12     700.0    None          NaT    None
11 2012-10-10     800.0    None          NaT    None
12 2012-06-07     500.0  annual   2012-06-26   2.17%
13 2009-08-03     250.0    None          NaT    None
14 2008-12-08    1250.0    None          NaT    None

In [22]:
investpy.get_stocks('VietNam')

,country,name,full_name,isin,currency,symbol
0,vietnam,An Phat Plastic and Green,An Phat Plastic and Green Environment JSC,VN000000AAA4,VND,AAA
1,vietnam,ACB,Asia Commercial Bank,VN000000ACB8,VND,ACB
2,vietnam,ADC,ADC,VN000000ADC4,VND,ADC
3,vietnam,Tan Binh Culture Co.,Tan Binh Culture Co.,VN000000ALT1,VND,ALT
4,vietnam,VAM,VAM,VN000000ALV7,VND,ALV
...,...,...,...,...,...,...
1321,vietnam,Ca Mau Seafood,Ca Mau Seafood Co Ltd,VN000000CAT0,VND,CAT
1322,vietnam,EVN Finance,EVN Finance JSC,VN000000EVF1,VND,EVF
1323,vietnam,Ho Nai Industrial Zone,Ho Nai Industrial Zone JSC,VN000000HIZ9,VND,HIZ
1324,vietnam,Quangninh Clean Water,Quangninh Clean Water JSC,VN000000NQN6,VND,NQN
1325,vietnam,Song Da 702 Hydroelectric,Song Da 702 Hydroelectric JSC,VN000000S727,VND,S72

In [29]:
investpy.stocks.get_stock_company_profile('AAA', country='VietNam', language='english')

{'url': 'https://www.investing.com/equities/an-phat.-jsc-company-profile',
 'desc': "An Phat Bioplastics Joint Stock Company, formerly known as An Phat Plastic and Green Environment Joint Stock Company is a Vietnam-based company engaged in the manufacture of plastic products. The Company’s products include t-shirt plastic bags, plastic films, food-covered bags, nylon films, bags on roll, garbage bags and die cut handle bags. It also provides printing and advertising on packages and offers other products, such as plastic cutting and packing machinery, plastic printer and flow machinery. The Company has three factories in Vietnam. During the year ended December 31, 2012, 92.5% of the Company's revenue came from the sale of finished products. As of December 31, 2012, the Company had one subsidiary named An Phat - Yen Bai Mineral & Plastic Joint Stock Company, which was active in stone exploitation and construction material trading. As of the same date, it had one affiliate."}